### ISSUE TITLE
Request: add keccak hash

### ISSUE THREAD

**Issue by hughjonesd** [shikokuchuo/secretbase#9]
There's currently no available R implementation of the keccak hash (though there are several of the closely related SHA3). It would be helpful to have one – I'm interfacing with an API that requires a keccak-hashed password. Maybe for other people too?

**Comment by shikokuchuo** [comment]
That seems reasonable. SHA-3 _is_ Keccak but just with a different padding parameter, and should be trivial to expose. I assume that Keccak-224/256/384/512 will cover everything you need?

**Comment by hughjonesd** [comment]
Yes, that would work for me!

**Comment by shikokuchuo** [comment]
This is now implemented in the dev version as `keccak()`. Please let me know if it works as expected for you.

**Comment by hughjonesd** [comment]
Works for me!

**Comment by shikokuchuo** [comment]
Great! I took the opportunity to more logically split out `sha3()` / `keccak()` / `shake256()` and I'll make a release shortly.
